# -*- coding: utf-8 -*-
"""SVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pKS-vUBBPzrJZCDGnoECDwGqKtLu5lcl
"""

print("hello world")

# support vector classifier
import pandas as pd
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn import datasets

df = datasets.load_iris(as_frame = True).frame

df.head()

df.isnull().sum()

df.info()

X =df.drop("target",axis= 1)
y =df["target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

y.head()

from sklearn.preprocessing import StandardScaler
Scaler = StandardScaler()
X_train_scaled = Scaler.fit_transform(X_train)
X_test_scaled = Scaler.transform(X_test)

X_train_scaled

print(X_train_scaled.shape, y_train.shape)

# build the model
svc = SVC()
svc.fit(X_train_scaled, y_train)

X_train_scaled.shape,y_train.shape

y_pred = svc.predict(X_test_scaled)

# evaluation
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score,classification_report
print("Accuracy",accuracy_score(y_test,y_pred))
print("accuracy_report ",classification_report(y_test,y_pred))
print("f1_score ", f1_score)
print("confusion_matrix",confusion_matrix(y_test,y_pred))

# linear kernel
svc = SVC(kernel = "linear")
svc.fit(X_train_scaled, y_train)
y_pred =svc.predict(X_test_scaled)
print("Accuracy",accuracy_score(y_test,y_pred))
print("accuracy_report ",classification_report(y_test,y_pred))
print("f1_score ", f1_score)

# sigmoid kernel

svc = SVC(kernel = "sigmoid")
svc.fit(X_train_scaled, y_train)
y_pred =svc.predict(X_test_scaled)
print("Accuracy",accuracy_score(y_test,y_pred))
print("accuracy_report ",classification_report(y_test,y_pred))
print("f1_score ", f1_score)

svm with  diiferent c-

C_vals =[0.5, 1,2,3,4,5]
for c_val in C_vals :
  svc = SVC(C=c_val, kernel ="rbf" )
  svc.fit(X_train_scaled, y_train)

  y_pred = svc.predict(X_test_scaled)
  print("C =",c_val,"& accuracy", accuracy_score(y_test,y_pred))

"""svr implementation"""



